name: build

on:
  push:
    branches: [ "Develop" ]
  pull_request:
    branches: [ "*" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          projectPath: ./

      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

      - name: Train-Adventure-Mobile CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: ✅Train-Adventure-Mobile-CI 성공! ✅
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 00FF00

      - name: Train-Adventure-Mobile CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: ❗️ Train-Adventure-Mobile-CI 실패! ❗️
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: FF0000
